export const cards = [
  {
    id: 1,
    title: "Website Developers",
    desc: "Showcase Your Services & Products",
    cat: "web",
    img: "./img/webbb.jpg",
  },
  {
    id: 2,
    title: "App Craftsmen",
    desc: "Enhance Your Brand Reputation",
    cat: "design",
    img: "./img/app.jpg",
  },
  {
    id: 3,
    title: "Game Creators",
    desc: "Turn Imaginations into Reality",
    cat: "web",
    img: "./img/game.jpg",
  },
  {
    id: 4,
    title: "Cyber Guardians",
    desc: "Secure Your Data from getting Leaked",
    cat: "music",
    img: "./img/cybersec.jpg",
  },
  {
    id: 5,
    title: "Data Analyst",
    desc: "Grow your Business by Analysing the Data",
    cat: "music",
    img: "./img/dataa.jpg",
  },
  {
    id: 6,
    title: "AI Visionaries",
    desc: "Add Intelligence in your Product",
    cat: "design",
    img: "./img/ai.jpg",
  },
  {
    id: 7,
    title: "DevOPs Engineer",
    desc: "Deploy Your Websites Easily",
    cat: "web",
    img: "./img/devvv.jpg",
  },
  {
    id: 8,
    title: "Software Builders",
    desc: "Build Your Entire Software",
    cat: "design",
    img: "./img/soft.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "./img/webdev.jpg",
    pp: "./img/sakshi.png",
    cat: "Website Developer",
    username: "Sakshi Bhojwani",
  },
  {
    id: 2,
    img: "./img/cloudcom.jpg",
    pp: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
    cat: "Cloud Engineer",
    username: "Atul Prasad",
  },
  {
    id: 3,
    img: "./img/dev.jpg",
    pp: "./img/meet3.jpg",
    cat: "DevOPs Engineer",
    username: "Meet Tilokani",
  },
  {
    id: 4,
    img: "./img/softwaredev.jpg",
    pp: "./img/aakash.png",
    cat: "Software Developer",
    username: "Aakash Pawar",
  },
  {
    id: 5,
    img: "./img/datalyst.jpg",
    pp: "./img/naruto.png",
    cat: "Data Analyst",
    username: "Naruto Uzumaki",
  },
  {
    id: 6,
    img: "./img/gamedev.jpg",
    pp: "./img/itachi.png",
    cat: "Game Artist",
    username: "Itachi Uchiha",
  },
  {
    id: 7,
    img: "./img/cyberr.jpg",
    pp: "./img/gon.png",
    cat: "Cyber Guardian",
    username: "Gon Freecss",
  },
  {
    id: 8,
    img: "./img/appdev.jpeg",
    pp: "./img/kuroko.jpg",
    cat: "App Developer",
    username: "Kuroko Tetsuya",
  },
];

export const gigs = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
    pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];
