export const cards = [
  {
    id: 1,
    title: "Website Developers",
    desc: "Showcase Your Services & Products",
    cat: "web",
    img: "./img/webbb.jpg",
  },
  {
    id: 2,
    title: "App Craftsmen",
    desc: "Enhance Your Brand Reputation",
    cat: "app",
    img: "./img/app.jpg",
  },
  {
    id: 3,
    title: "Game Creators",
    desc: "Turn Imaginations into Reality",
    cat: "game",
    img: "./img/game.jpg",
  },
  {
    id: 4,
    title: "Cyber Guardians",
    desc: "Secure Your Data from getting Leaked",
    cat: "cyber",
    img: "./img/cybersec.jpg",
  },
  {
    id: 5,
    title: "Data Analyst",
    desc: "Grow your Business by Analysing the Data",
    cat: "data",
    img: "./img/dataa.jpg",
  },
  {
    id: 6,
    title: "AI Visionaries",
    desc: "Add Intelligence in your Product",
    cat: "ai",
    img: "./img/ai.jpg",
  },
  {
    id: 7,
    title: "DevOPs Engineer",
    desc: "Deploy Your Websites Easily",
    cat: "dev",
    img: "./img/devvv.jpg",
  },
  {
    id: 8,
    title: "Software Builders",
    desc: "Build Your Entire Software",
    cat: "soft",
    img: "./img/soft.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "./img/webdev.jpg",
    pp: "./img/sakshi.png",
    cat: "Website Developer",
    username: "Sakshi Bhojwani",
  },
  {
    id: 2,
    img: "./img/cloudcom.jpg",
    pp: "./img/atul.jpeg",
    cat: "Cloud Engineer",
    username: "Atul Prasad",
  },
  {
    id: 3,
    img: "./img/dev.jpg",
    pp: "./img/meet3.jpg",
    cat: "DevOPs Engineer",
    username: "Meet Tilokani",
  },
  {
    id: 4,
    img: "./img/softwaredev.jpg",
    pp: "./img/aakash.png",
    cat: "Software Developer",
    username: "Aakash Pawar",
  },
  {
    id: 5,
    img: "./img/datalyst.jpg",
    pp: "./img/naruto.png",
    cat: "Data Analyst",
    username: "Naruto Uzumaki",
  },
  {
    id: 6,
    img: "./img/gamedev.jpg",
    pp: "./img/itachi.png",
    cat: "Game Artist",
    username: "Itachi Uchiha",
  },
  {
    id: 7,
    img: "./img/cyberr.jpg",
    pp: "./img/gon.png",
    cat: "Cyber Guardian",
    username: "Gon Freecss",
  },
  {
    id: 8,
    img: "./img/appdev.jpeg",
    pp: "./img/kuroko.jpg",
    cat: "App Developer",
    username: "Kuroko Tetsuya",
  },
];

